########################################################
# Start Loan Application
########################################################

# @name startLoanApplication

POST http://localhost:5108/LoanApplication
Content-Type: application/json

{
    "ApplicantName": "Eric Grey",
    "LoanAmount": 80000,
    "YearlyGrossSalary": 80000
}

###

########################################################
# Get workflow instance
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

GET http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}

### 

########################################################
# LoanAssessmentCompleted using Web API
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:5108/LoanApplication/{{instanceId}}/RaiseLoanAssessmentCompleted
Content-Type: application/json

{
    "Approved": true
}

### 

########################################################
# LoanAssessmentCompleted using Dapr sidecar
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}/raiseEvent/LoanAssessmentCompleted
Content-Type: application/json

{
    "Approved": true
}

### 

########################################################
# CustomerProposalDecisionReceived using Web API
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:5108/LoanApplication/{{instanceId}}/RaiseCustomerProposalDecisionReceived
Content-Type: application/json

{
    "Accepted": true
}

### 

########################################################
# CustomerProposalDecisionReceived using Dapr sidecar
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}/raiseEvent/CustomerProposalDecisionReceived
Content-Type: application/json

{
    "Accepted": true
}

### 

########################################################
# CustomerContactedForProposal using Web API
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:5108/LoanApplication/{{instanceId}}/RaiseCustomerContactedForProposal
Content-Type: application/json

{
    "Accepted": true
}

### 

########################################################
# CustomerContactedForProposal using Dapr sidecar
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}/raiseEvent/CustomerContactedForProposal
Content-Type: application/json

{
    "Accepted": true
}
