########################################################
# Start Loan Application
########################################################

# @name startLoanApplication

POST http://localhost:5108/LoanApplication
Content-Type: application/json

{
    "ApplicantName": "Eric White",
    "LoanAmount": 80000,
    "YearlyGrossSalary": 80000
}

### 

########################################################
# LoanAssessmentCompleted
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}/raiseEvent/LoanAssessmentCompleted
Content-Type: application/json

{
    "Approved": true
}

### 

########################################################
# CustomerProposalDecisionReceived
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}/raiseEvent/CustomerProposalDecisionReceived
Content-Type: application/json

{
    "Accepted": true
}

### 

########################################################
# CustomerContactedForProposal
########################################################

@instanceId = {{startLoanApplication.response.body.$.instanceId}}

POST http://localhost:3500/v1.0-alpha1/workflows/dapr/{{instanceId}}/raiseEvent/CustomerContactedForProposal
Content-Type: application/json

{
    "Accepted": true
}
